# Site settings
title: Journal
header-img: img/post-bg-04.jpg
email: lurie.jo@gmail.com
description: "This is mostly about writing things."
baseurl: ""
url: "http://jonathanlurie.github.io/"
twitter_username: jonathanlurie
github_username:  jonathanlurie
facebook_username:  jonathan.lurie

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
